Task 5
JZasinets/mentoring pull request #4
Opened 2021-09-01 17:56 UTC by JZasinets

2021-09-03 08:44 UTC, ragozin-nikita requested changes

2021-09-03 08:44 UTC, ragozin-nikita commented on src/array.js
> +        const isContainsNumbers = arrayValue.every(function(result, val) {return result && typeof val === 'number'});
Пожалуйста используй стрелочную функцию

2021-09-03 08:44 UTC, ragozin-nikita commented on src/array.js
> +            const uniqueValue = Array.from(new Set(arrayValue));
Супер! А сможешь сделать тоже самое с деструктуризацией?

2021-09-03 08:44 UTC, ragozin-nikita commented on src/fibonacci.js
> +            let a = 0;
Используй объясняющие имена для переменных

2021-09-03 08:44 UTC, ragozin-nikita commented on src/logOut.js
> +        if (timeLeft == 5) console.log(`${timeLeft} секунд,`);
https://gist.github.com/realmyst/1262561
Попробуй добавить этот хелпер в приложение и сделать с ним ;)

2021-09-03 08:44 UTC, ragozin-nikita commented on src/logOut.js
> +        if (timeLeft == 1) console.log(`${timeLeft} секунда`);
```suggestion
        if (timeLeft === 1) console.log(`${timeLeft} секунда`);
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality

Это очень важно знать!

2021-09-03 12:00 UTC, JZasinets commented on src/array.js
> +        const isContainsNumbers = arrayValue.every(function(result, val) {return result && typeof val === 'number'});
Готово

2021-09-03 12:00 UTC, JZasinets commented on src/fibonacci.js
> +            let a = 0;
Готово

2021-09-03 12:00 UTC, JZasinets commented on src/logOut.js
> +        if (timeLeft == 5) console.log(`${timeLeft} секунд,`);
Готово

2021-09-07 03:40 UTC, ragozin-nikita requested changes

2021-09-07 03:40 UTC, ragozin-nikita commented on src/array.js
> +            const [uniqueValue] = [new Set(arrayValue)];
```suggestion
            const uniqueValues = [...new Set(arrayValue)];
```

2021-09-07 03:40 UTC, ragozin-nikita commented on src/array.js
> +            console.log(`Уникальные значения: ${[...uniqueValue]}`);
```suggestion
            console.log(`Уникальные значения: ${uniqueValues}`);
```

2021-09-08 04:01 UTC, ragozin-nikita commented on functions.js
> +let namedArguments = ({ parameterA, parameterB, parameterC = {} }) => {
Зачем здесь = {}?

2021-09-10 06:37 UTC, ragozin-nikita requested changes

2021-09-10 06:37 UTC, ragozin-nikita commented on functions.js
> +    const argumentsArray = [...arguments];
```suggestion
    const argumentsArray = arguments;
```

2021-09-10 06:37 UTC, ragozin-nikita commented on functions.js
> +let namedArguments = ({ parameterA, parameterB, parameterC }) => {
```suggestion
let namedArguments = ({ first, secod, third }) => {
```

2021-09-10 06:37 UTC, ragozin-nikita commented on functions.js
> +let noNamedArguments = (firstArgument, secondArgument, ...otherArguments) => {
```suggestion
let noNamedArguments = (first, second, ...other) => {
```

2021-09-10 06:37 UTC, ragozin-nikita commented on src/array.js
> +        const arrayValue = stringValue.split(' ').join('').split(',');
Переписать через регулярное выражение в `.replace()`

2021-09-10 06:37 UTC, ragozin-nikita commented on src/array.js
> +        const isContainsNumbers = arrayValue.every((result, val) => {return result && typeof val === 'number'});
```suggestion
        const isContainsNumbers = arrayValue.every((result, val) => result && typeof val === 'number');
```

2021-09-10 06:37 UTC, ragozin-nikita commented on src/array.js
> +        const arrayValue = stringValue.split(' ').join('').split(',');
regexp 101

2021-09-10 07:32 UTC, merged